version: '3.9'
services:
  backend:
    networks:
      - mynetwork
      - mynetwork2
      - mynetwork3
    build: app/
    ports:
      - '9999:8000'
    depends_on:
      - db
    env_file: 
      - .env

  db:
    networks:
      - mynetwork
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    
  client:
    networks:
      - mynetwork2
    build: client/
    depends_on:
      - backend
    env_file:
      - .env

  background_processor:
    networks:
      - mynetwork3
    build: background_processor/
    depends_on:
      - backend
    volumes:
      - ./shared_resource:/app/shared_resource
networks:
  mynetwork:
  mynetwork2:
  mynetwork3: